#
# Module manifest for module 'OMG.PSUtilities.AzureCore'
#
# Generated by: Lakshmanachari Panuganti
#
# Generated on: 7/15/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'OMG.PSUtilities.AzureCore.psm1'

    # Version number of this module.
    ModuleVersion     = '1.2.0'

    # Supported PSEditions
    # Tested: imports and resolves all exports on PowerShell 7 (Core). Windows PowerShell 5.1
    # (Desktop) is blocked by the PowerShellVersion 7.0 floor below, so Core is the only
    # edition this module is claimed to support.
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID              = '6ca653ef-4fa6-41a0-9873-7a9b112feeaf'

    # Author of this module
    Author            = 'Lakshmanachari Panuganti'

    # Company or vendor of this module
    CompanyName       = 'OMG IT Solutions'

    # Copyright statement for this module
    Copyright         = '(c) 2025-2026 Lakshmanachari Panuganti'

    # Description of the functionality provided by this module
    Description       = 'Core Azure-related scripting, including identity and subscription management.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module.
    # Az.Accounts is universally required: three of the four exports depend on the Az context.
    # Microsoft.Graph.*, kubectl, and ThreadJob are optional and are resolved at call time by
    # the functions that need them, so they are deliberately not declared here.
    RequiredModules   = @('OMG.PSUtilities.Core', 'Az.Accounts')

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Get-PSUAzToken',
        'Get-PSUk8sPodLabel',
        'Invoke-PSUAzureAppRegAudit',
        'Test-PSUAzConnection'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('Azure', 'AzureCore', 'Identity', 'DevOps', 'PowerShell', 'Automation', 'OMG')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/lakshmanachari-panuganti/OMG.PSUtilities/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/lakshmanachari-panuganti/OMG.PSUtilities'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
1.2.0
- Declared Az.Accounts as a required module. It was always needed by Get-PSUAzToken,
  Test-PSUAzConnection, and Invoke-PSUAzureAppRegAudit, but was never declared. Installs
  now pull it automatically; environments that lack it will fail at import instead of
  failing later inside a command.
- Declared CompatiblePSEditions = Core, from tested imports rather than assumption.
- Guarded the optional kubectl and ThreadJob dependencies in Get-PSUk8sPodLabel with
  actionable messages instead of a raw CommandNotFoundException.
- Applied the MIT license metadata approved in docs/decisions/0.5-licensing-selection.md.
- Removed seven unreferenced --wip files from Public/. They were already excluded by the
  loader and were never exported, so this is not a functional change.
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
