#
# Module manifest for module 'OMG.PSUtilities.Core'
#
# Generated by: Lakshmanachari Panuganti
#
# Generated on: 7/15/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'OMG.PSUtilities.Core.psm1'

    # Version number of this module.
    ModuleVersion        = '1.1.0'

    # Supported PSEditions
    # Tested: imports and exports every command on both Windows PowerShell 5.1 (Desktop) and
    # PowerShell 7 (Core), consistent with the PowerShellVersion 5.1 floor below.
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = '02725827-97c9-4b6e-bafa-f5004e42e1a5'

    # Author of this module
    Author               = 'Lakshmanachari Panuganti'

    # Company or vendor of this module
    CompanyName          = 'OMG IT Solutions'

    # Copyright statement for this module
    Copyright            = '(c) 2025-2026 Lakshmanachari Panuganti'

    # Description of the functionality provided by this module
    Description          = 'General purpose PowerShell utilities and system-level tools.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module.
    # ImportExcel is the only hard dependency; Export-PSUExcel is unusable without it.
    # ThreadJob is deliberately absent: Get-PSUPublicIP no longer uses Start-ThreadJob, so
    # Core does not push that dependency onto every module that requires it.
    RequiredModules      = @(
        @{ ModuleName = 'ImportExcel'; ModuleVersion = '7.8.9' }
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'Approve-PSUGithubPullRequest',
        'Approve-PSUPullRequest',
        'Complete-PSUGithubPullRequest',
        'Complete-PSUPullRequest',
        'Export-PSUExcel',
        'Find-PSUFilesContainingText',
        'Get-PSUConnectedWifiInfo',
        'Get-PSUCredentialFromManager',
        'Get-PSUCredentialManagerInventory',
        'Get-PSUFunctionCommentBasedHelp',
        'Get-PSUGitFileChangeMetadata',
        'Get-PSUInstalledSoftware',
        'Get-PSUModule',
        'Get-PSUPublicIP',
        'Get-PSUUserEnvironmentVariable',
        'Get-PSUUserSession',
        'New-PSUGithubPullRequest',
        'New-PSUHTMLReport',
        'New-PSUOutlookMeeting',
        'Remove-PSUCredentialFromManager',
        'Remove-PSUUserEnvironmentVariable',
        'Remove-PSUUserSession',
        'Send-PSUHTMLReport',
        'Send-PSUTeamsMessage',
        'Set-PSUCredentialToManager',
        'Set-PSUUserEnvironmentVariable',
        'Test-PSUInternetConnection',
        'Uninstall-PSUInstalledSoftware',
        'Unlock-PSUTerraformStateAWS',
        'Update-OMGModuleVersion'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @(
        'fetchcred',
        'Get-WifiInfo',
        'listcred',
        'Remove-PSUInstalledSoftware',
        'setcred',
        'Uninstall-Software'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('Utilities', 'SystemTools', 'DevOps', 'PowerShell', 'Automation', 'OMG')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/lakshmanachari-panuganti/OMG.PSUtilities/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/lakshmanachari-panuganti/OMG.PSUtilities'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
1.1.0
- Get-PSUPublicIP no longer uses Start-ThreadJob. Its HTTP fallback now queries the endpoints
  in turn and takes the first valid address. On Windows PowerShell 5.1, which does not ship
  ThreadJob, that fallback previously raised CommandNotFoundException instead of returning an
  address. A total outage of all four endpoints can now take up to four times TimeoutSec.
- Declared CompatiblePSEditions = Desktop, Core, from tested imports rather than assumption.
- ImportExcel remains the only required module; ThreadJob is deliberately not declared.
- Applied the MIT license metadata approved in docs/decisions/0.5-licensing-selection.md.
- Removed two unreferenced --wip files from Public/.
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
